### ISSUE TITLE
Client from "latest" binaries reports version is "latest"

### ISSUE THREAD

**Issue by afrittoli** [apache/incubator-openwhisk-wskdeploy#1000]
I just installed wskdeploy from the latest binary package for Mac amd64 (https://github.com/apache/incubator-openwhisk-wskdeploy/releases/download/latest/openwhisk_wskdeploy-latest-mac-amd64.zip). 

When asking for the version the client reports "latest" which is not very useful, since this information is obtained from the local binary, which means it's almost always stale.

```
$ wskdeploy version
wskdeploy version: latest
```

**Comment by houshengbo** [comment]
@afrittoli Each commit to the master branch will kick-off the travis job to build the binaries with the tag "latest" automatically. The key work "latest" is used as the version, and we do not pick up any other key word for the version purpose.

A meaningful version name is added when a commit is tagged, so that the tag name is used as the version to generate the binaries.

**Comment by AnthonyAmanse** [comment]
@houshengbo I think adding like a date and the latest commit SHA fingerprint would be useful. Something like `latest-12-05-2018-<commit-sha>`. This makes it easier for users to sync/compare their local `wskdeploy` binaries to what's on the upstream's "latest".

Side question: Is the `0.9.9` version the stable and recommended version?

**Comment by rabbah** [comment]
Great suggestion @AnthonyAmanse  - are you interested in submitting a PR?
