### ISSUE TITLE
Provide some yaml quick fail or validation mechanism to avoid confusing errors.

### ISSUE THREAD

**Issue by lzbj** [apache/incubator-openwhisk-wskdeploy#148]
When I try to add support to data processing use cases etc, I found it's a little difficult to make the deployment, manifest yaml correct, and I got null pointer errors with yaml parsers. 
For example, if the deployment.yaml lacks the package->name property, there will be null pointer 
errors, the error could bypass the yaml parser check

So is there a way to fast validate the yaml correctness, something like xml schema for xml and java?

**Comment by paulcastro** [comment]
This is a good point. We need a validator since its very easy to make mistakes in the YAML files.  In addition to a validator,  letting wskdeploy itself create and modify the YAML file through commands like `wskdeploy add action .....` might also be useful.  @lionelvillard comments on your ideas around this?

**Comment by lionelvillard** [comment]
My suggestion would be to add a `validation` command based on an explicit schema formally describing the specification. We can either use JSON schema or Rx, but JSON schema is probably a much better choice (much bigger community). https://github.com/ghodss/yaml can be use to convert `YAML` to `JSON`.

**Comment by lzbj** [comment]
close as PR #152 merged.
