### ISSUE TITLE
Add support for Swift version 3.1.1 "kind"

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#277]
Add support for Swift version 3.1.1 as per:
https://github.com/apache/incubator-openwhisk/pull/2120

Our supported "kinds" include only (according to spec.):

swift@3, swift@2
where default is swift@3 if just "swift" is supplied.

@paulcastro thoughts?

**Comment by paulcastro** [comment]
The semantics may be changing. In the past, minor and patch level changes to Swift were just updates to the major version kind.  This meant that, for example, 2.0.1 would replace 2.0.0 and the kind `swift:2` (actually the label was `swift`) would not change.

We now have to retain binary level compatibility so even patch level changes will create a new kind.  Right now we support `swift:3` and very soon `swift:3.1.1`, with `swift:4.0.0` just around the corner.

This means the nature of `swift:default` is likely going mean "whatever the latest stable version" is.  @rabbah and @bjustin-ibm suggested using `swift:latest` instead of `swift:latest`.  It may also make sense to have `swift:development` that points to some relatively stable version of a Swift alpha or beta release.

What does deprecation really mean? I think the latest thought on this is that we don't have to remove a kind when we deprecate it.  It will just mean its no longer supported and we won't test it anymore.

**Comment by mrutkows** [comment]
OpenWhisk support the use of the "curl" command to query supported runtimes. 
I myself just tried it against bluemix:

Matt$ curl -k https://openwhisk.ng.bluemix.net
{
"support": {
"github": "https://github.com/apache/incubator-openwhisk/issues",
"slack": "http://slack.openwhisk.org"
},
"description": "OpenWhisk",
"api_paths": ["/api/v1"],
"runtimes": {
"nodejs": [{
"image": "openwhisk/nodejsaction:latest",
"deprecated": true,
"requireMain": false,
"default": false,
"attached": false,
"kind": "nodejs"
}, {
"image": "openwhisk/nodejs6action:latest",
"deprecated": false,
"requireMain": false,
"default": true,
"attached": false,
"kind": "nodejs:6"
}],
"java": [{
"image": "openwhisk/java8action:latest",
"deprecated": false,
"requireMain": true,
"default": true,
"attached": true,
"kind": "java"
}],
"php": [{
"image": "openwhisk/action-php-v7.1:latest",
"deprecated": false,
"requireMain": false,
"default": true,
"attached": false,
"kind": "php:7.1"
}],
"python": [{
"image": "openwhisk/python2action:latest",
"deprecated": false,
"requireMain": false,
"default": false,
"attached": false,
"kind": "python"
}, {
"image": "openwhisk/python2action:latest",
"deprecated": false,
"requireMain": false,
"default": true,
"attached": false,
"kind": "python:2"
}, {
"image": "openwhisk/python3action:latest",
"deprecated": false,
"requireMain": false,
"default": false,
"attached": false,
"kind": "python:3"
}],
"swift": [{
"image": "openwhisk/swiftaction:latest",
"deprecated": true,
"requireMain": false,
"default": false,
"attached": false,
"kind": "swift"
}, {
"image": "openwhisk/swift3action:latest",
"deprecated": false,
"requireMain": false,
"default": true,
"attached": false,
"kind": "swift:3"
}, {
"image": "openwhisk/action-swift-v3.1.1:latest",
"deprecated": false,
"requireMain": false,
"default": false,
"attached": false,
"kind": "swift:3.1.1"
}]
},
"limits": {
"actions_per_minute": 5000,
"triggers_per_minute": 5000,
"concurrent_actions": 1000
}
}

**Comment by mrutkows** [comment]
Updated spec. v0.8.8 with latest values as if Aug. 2017
