### ISSUE TITLE
Integration Test - Alarm Trigger

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#349]
Create an integration test for validating [alarm trigger](https://github.com/apache/incubator-openwhisk-wskdeploy/tree/master/tests/usecases/alarmtrigger) usecase.

Integration tests are located under [tests/src/integration](https://github.com/apache/incubator-openwhisk-wskdeploy/tree/master/tests/src/integration). Create a new folder named "alarmtrigger" under tests/src/integration.

Remove [alarm trigger](https://github.com/apache/incubator-openwhisk-wskdeploy/tree/master/tests/usecases/alarmtrigger) from usecase folder.

**Comment by houshengbo** [comment]
@mrutkows @pritidesai We do not have alarm service available in openwhisk deployed in Travis. Shall we point to openwhisk services on top of bluemix for the tests? I suggest we need anther type of test called bluemix-integration parallel to integration tests. Otherwise, if developers run all the integration tests locally, the bluemix dependent tests will fail.
