### ISSUE TITLE
Move manifest.yml and manifest.yaml out of integration test

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#381]
Integration tests should not have manifest.yaml and manifest.yml files. Please move them to https://github.com/apache/incubator-openwhisk-wskdeploy/tree/master/tests/dat and convert the following integration tests into unit tests:

TestSupportManifestYamlPath
TestSupportManifestYmlPath
TestSupportManifestYamlDeployment
TestSupportManifestYmlDeployment

Our integration tests should define manifest and deployment of any legit application.

**Comment by daisy-ycguo** [comment]
@pritidesai I don't quite understand this issue.
These four tests invoke the command `wskdeploy` to deploy action (src: `tests/src/integration/flagstests/src/greeting.js`) to OpenWhisk server. I think it's a kind of integration tests not unit test. Because unit test will not set up OpenWhisk server and will not exec the deployment to real OpenWhisk server. What's more, I noticed there were several manifest.yaml and deployment.yaml in sub folders of `tests/src/integration`. Then what's the meaning to only remove manifest.yaml and manifest.yml under folder `tests/src/integration/flagstests/`?

if we move these four functions to unit test, how to handle the dependencies to real OpenWhisk server and the source code `tests/src/integration/flagstests/src/greeting.js`? Any suggestions about the changes of test logic ?

**Comment by pritidesai** [comment]
Hi @daisy-ycguo sorry for the confusion, the whole point of this issue was to get rid of`manifest.yml` from https://github.com/apache/incubator-openwhisk-wskdeploy/tree/master/tests/src/integration/runtimetests, which is already deleted (as part of PR #408). We want to standardize our integration test and have only one manifest and one deployment under any integration test.

We still want to add unit test to validate that wskdeploy honors `.yaml` and `.yml` extension and have those files under `tests/dat`.

**Comment by daisy-ycguo** [comment]
@pritidesai again, if we want to validate `wskdeploy` honors .yaml and iml extension, we need a OpenWhisk runtime environment. But during unit test, we don't have such environment. Then how can we test `wskdeploy` in the unit test ?
